# permissions for end users to view pulpbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pulpbackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pulp-operator
    app.kubernetes.io/part-of: pulp-operator
    app.kubernetes.io/managed-by: kustomize
  name: pulpbackup-viewer-role
rules:
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups/status
  verbs:
  - get
