apiVersion: repo-manager.pulpproject.org/v1
kind: Pulp
metadata:
  name: example
spec:
  ingress_type: nodeport
  api:
    replicas: 1
  cache:
    enabled: true
  content:
    replicas: 2
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 2
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi

  database:
    postgres_storage_class: standard

  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "2Gi"
  file_storage_storage_class: standard
