---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  analytics: "False"
  token_server: '"http://nodeport.local:30000/token/"'
  content_origin: '"http://nodeport.local:30000"'
  ansible_api_hostname: '"http://nodeport.local:30000"'
  api_root: '"/pulp/"'
  allowed_export_paths: '[ "/tmp" ]'
  allowed_import_paths: '[ "/tmp" ]'
  aws_s3_endpoint_url: '"http://pulp_minio:9000"'

---
apiVersion: repo-manager.pulpproject.org/v1
kind: Pulp
metadata:
  name: test-pulp
spec:
  image: quay.io/pulp/pulp-minimal
  image_version: stable
  image_web: quay.io/pulp/pulp-web
  image_web_version: stable
  admin_password_secret: "example-pulp-admin-password"
  ingress_type: nodeport
  nodeport_port: 30000
  object_storage_s3_secret: example-pulp-object-storage

  custom_pulp_settings: settings

  api:
    replicas: 1
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi

  database:
    postgres_storage_class: standard
