/*
Pulp 3 API

Testing ContentPackagecategoriesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpbindings

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pulp/pulp-operator/bindings/release"
)

func Test_pulpbindings_ContentPackagecategoriesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentPackagecategoriesAPIService ContentRpmPackagecategoriesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContentPackagecategoriesAPI.ContentRpmPackagecategoriesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentPackagecategoriesAPIService ContentRpmPackagecategoriesRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rpmPackageCategoryHref string

		resp, httpRes, err := apiClient.ContentPackagecategoriesAPI.ContentRpmPackagecategoriesRead(context.Background(), rpmPackageCategoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentPackagecategoriesAPIService ContentRpmPackagecategoriesSetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rpmPackageCategoryHref string

		resp, httpRes, err := apiClient.ContentPackagecategoriesAPI.ContentRpmPackagecategoriesSetLabel(context.Background(), rpmPackageCategoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentPackagecategoriesAPIService ContentRpmPackagecategoriesUnsetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rpmPackageCategoryHref string

		resp, httpRes, err := apiClient.ContentPackagecategoriesAPI.ContentRpmPackagecategoriesUnsetLabel(context.Background(), rpmPackageCategoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
