/*
Pulp 3 API

Testing PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpbindings

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pulp/pulp-operator/bindings/release"
)

func Test_pulpbindings_PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPIService PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var distroBasePath string
		var name string
		var namespace string

		resp, httpRes, err := apiClient.PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPI.PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexDelete(context.Background(), distroBasePath, name, namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPIService PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var distroBasePath string

		resp, httpRes, err := apiClient.PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPI.PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexList(context.Background(), distroBasePath).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPIService PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var distroBasePath string
		var name string
		var namespace string

		resp, httpRes, err := apiClient.PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPI.PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexRead(context.Background(), distroBasePath, name, namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPIService PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var distroBasePath string
		var name string
		var namespace string

		resp, httpRes, err := apiClient.PulpAnsibleDefaultPluginAnsibleContentCollectionsIndexAPI.PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsIndexUpdate(context.Background(), distroBasePath, name, namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
