/*
Pulp 3 API

Testing PulpAnsibleDefaultPluginAnsibleContentCollectionsArtifactsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpbindings

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pulp/pulp-operator/bindings/release"
)

func Test_pulpbindings_PulpAnsibleDefaultPluginAnsibleContentCollectionsArtifactsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PulpAnsibleDefaultPluginAnsibleContentCollectionsArtifactsAPIService PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsArtifactsDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var distroBasePath string
		var filename string

		httpRes, err := apiClient.PulpAnsibleDefaultPluginAnsibleContentCollectionsArtifactsAPI.PulpAnsibleGalaxyDefaultPluginAnsibleContentCollectionsArtifactsDownload(context.Background(), distroBasePath, filename).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
