/*
Pulp 3 API

Testing PulpAnsibleDefaultArtifactsCollectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpbindings

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pulp/pulp-operator/bindings/release"
)

func Test_pulpbindings_PulpAnsibleDefaultArtifactsCollectionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PulpAnsibleDefaultArtifactsCollectionsAPIService PulpAnsibleGalaxyDefaultArtifactsCollectionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var filename string
		var path string

		httpRes, err := apiClient.PulpAnsibleDefaultArtifactsCollectionsAPI.PulpAnsibleGalaxyDefaultArtifactsCollectionsGet(context.Background(), filename, path).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
