/*
Pulp 3 API

Testing DistributionsAptAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpbindings

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pulp/pulp-operator/bindings/release"
)

func Test_pulpbindings_DistributionsAptAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DistributionsAptAPIService DistributionsDebAptAddRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptAddRole(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptDelete(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptListRoles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptListRoles(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptMyPermissions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptMyPermissions(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptPartialUpdate(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptRead(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptRemoveRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptRemoveRole(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptSetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptSetLabel(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptUnsetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptUnsetLabel(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DistributionsAptAPIService DistributionsDebAptUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var debAptDistributionHref string

		resp, httpRes, err := apiClient.DistributionsAptAPI.DistributionsDebAptUpdate(context.Background(), debAptDistributionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
