/*
Pulp 3 API

Testing ContentArtifactAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpbindings

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pulp/pulp-operator/bindings/release"
)

func Test_pulpbindings_ContentArtifactAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentArtifactAPIService ContentMavenArtifactCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContentArtifactAPI.ContentMavenArtifactCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentArtifactAPIService ContentMavenArtifactList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContentArtifactAPI.ContentMavenArtifactList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentArtifactAPIService ContentMavenArtifactRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mavenMavenArtifactHref string

		resp, httpRes, err := apiClient.ContentArtifactAPI.ContentMavenArtifactRead(context.Background(), mavenMavenArtifactHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentArtifactAPIService ContentMavenArtifactSetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mavenMavenArtifactHref string

		resp, httpRes, err := apiClient.ContentArtifactAPI.ContentMavenArtifactSetLabel(context.Background(), mavenMavenArtifactHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentArtifactAPIService ContentMavenArtifactUnsetLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mavenMavenArtifactHref string

		resp, httpRes, err := apiClient.ContentArtifactAPI.ContentMavenArtifactUnsetLabel(context.Background(), mavenMavenArtifactHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
