/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pulpbindings

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// PluginSearchCollectionVersionsAPIService PluginSearchCollectionVersionsAPI service
type PluginSearchCollectionVersionsAPIService service

type PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest struct {
	ctx context.Context
	ApiService *PluginSearchCollectionVersionsAPIService
	ansibleCrossRepositoryCollectionVersionIndexHref string
	xTaskDiagnostics *[]string
	dependency *string
	deprecated *bool
	distribution *[]string
	distributionBasePath *[]string
	highest *bool
	isDeprecated *bool
	isHighest *bool
	isSigned *bool
	keywords *string
	limit *int32
	name *string
	namespace *string
	offset *int32
	orderBy *[]string
	q *string
	repository *[]string
	repositoryLabel *string
	repositoryName *[]string
	repositoryVersion *string
	signed *bool
	tags *string
	version *string
	versionRange *string
	fields *[]string
	excludeFields *[]string
}

// List of profilers to use on tasks.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) XTaskDiagnostics(xTaskDiagnostics []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Dependency(dependency string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.dependency = &dependency
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Deprecated(deprecated bool) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.deprecated = &deprecated
	return r
}

// Filter collectionversions that are in these distrubtion ids.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Distribution(distribution []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.distribution = &distribution
	return r
}

// Filter collectionversions that are in these base paths.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) DistributionBasePath(distributionBasePath []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.distributionBasePath = &distributionBasePath
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Highest(highest bool) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.highest = &highest
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) IsDeprecated(isDeprecated bool) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.isDeprecated = &isDeprecated
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) IsHighest(isHighest bool) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.isHighest = &isHighest
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) IsSigned(isSigned bool) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.isSigned = &isSigned
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Keywords(keywords string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.keywords = &keywords
	return r
}

// Number of results to return per page.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Limit(limit int32) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.limit = &limit
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Name(name string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.name = &name
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Namespace(namespace string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.namespace = &namespace
	return r
}

// The initial index from which to return the results.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Offset(offset int32) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.offset = &offset
	return r
}

// Ordering* &#x60;pulp_created&#x60; - by CV created* &#x60;-pulp_created&#x60; - by CV created (descending)* &#x60;namespace&#x60; - by CV namespace* &#x60;-namespace&#x60; - by CV namespace (descending)* &#x60;name&#x60; - by CV name* &#x60;-name&#x60; - by CV name (descending)* &#x60;version&#x60; - by CV version* &#x60;-version&#x60; - by CV version (descending)
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) OrderBy(orderBy []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.orderBy = &orderBy
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Q(q string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.q = &q
	return r
}

// Filter collectionversions that are in these repository ids.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Repository(repository []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.repository = &repository
	return r
}

// Filter labels by search string
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) RepositoryLabel(repositoryLabel string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.repositoryLabel = &repositoryLabel
	return r
}

// Filter collectionversions that are in these repositories.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) RepositoryName(repositoryName []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.repositoryName = &repositoryName
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) RepositoryVersion(repositoryVersion string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.repositoryVersion = &repositoryVersion
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Signed(signed bool) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.signed = &signed
	return r
}

// Filter by comma separate list of tags that must all be matched
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Tags(tags string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.tags = &tags
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Version(version string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.version = &version
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) VersionRange(versionRange string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.versionRange = &versionRange
	return r
}

// A list of fields to include in the response.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Fields(fields []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.fields = &fields
	return r
}

// A list of fields to exclude from the response.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) ExcludeFields(excludeFields []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) Execute() (*PaginatedCollectionVersionSearchListResponseList, *http.Response, error) {
	return r.ApiService.PluginAnsibleSearchCollectionVersionsListExecute(r)
}

/*
PluginAnsibleSearchCollectionVersionsList List cross repository collection version indexs

A viewset for cross-repo searches.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param ansibleCrossRepositoryCollectionVersionIndexHref
 @return PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest
*/
func (a *PluginSearchCollectionVersionsAPIService) PluginAnsibleSearchCollectionVersionsList(ctx context.Context, ansibleCrossRepositoryCollectionVersionIndexHref string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest {
	return PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest{
		ApiService: a,
		ctx: ctx,
		ansibleCrossRepositoryCollectionVersionIndexHref: ansibleCrossRepositoryCollectionVersionIndexHref,
	}
}

// Execute executes the request
//  @return PaginatedCollectionVersionSearchListResponseList
func (a *PluginSearchCollectionVersionsAPIService) PluginAnsibleSearchCollectionVersionsListExecute(r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsListRequest) (*PaginatedCollectionVersionSearchListResponseList, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PaginatedCollectionVersionSearchListResponseList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PluginSearchCollectionVersionsAPIService.PluginAnsibleSearchCollectionVersionsList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{ansible_cross_repository_collection_version_index_href}api/v3/plugin/ansible/search/collection-versions/"
	localVarPath = strings.Replace(localVarPath, "{"+"ansible_cross_repository_collection_version_index_href"+"}", url.PathEscape(parameterValueToString(r.ansibleCrossRepositoryCollectionVersionIndexHref, "ansibleCrossRepositoryCollectionVersionIndexHref")), -1)
        localVarPath = strings.Replace(localVarPath, "/%2F", "/", -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.dependency != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "dependency", r.dependency, "form", "")
	}
	if r.deprecated != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "deprecated", r.deprecated, "form", "")
	}
	if r.distribution != nil {
		t := *r.distribution
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "distribution", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "distribution", t, "form", "multi")
		}
	}
	if r.distributionBasePath != nil {
		t := *r.distributionBasePath
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "distribution_base_path", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "distribution_base_path", t, "form", "multi")
		}
	}
	if r.highest != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "highest", r.highest, "form", "")
	}
	if r.isDeprecated != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "is_deprecated", r.isDeprecated, "form", "")
	}
	if r.isHighest != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "is_highest", r.isHighest, "form", "")
	}
	if r.isSigned != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "is_signed", r.isSigned, "form", "")
	}
	if r.keywords != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "keywords", r.keywords, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.name != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name", r.name, "form", "")
	}
	if r.namespace != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "namespace", r.namespace, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.orderBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "order_by", r.orderBy, "form", "csv")
	}
	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	if r.repository != nil {
		t := *r.repository
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "repository", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "repository", t, "form", "multi")
		}
	}
	if r.repositoryLabel != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_label", r.repositoryLabel, "form", "")
	}
	if r.repositoryName != nil {
		t := *r.repositoryName
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "repository_name", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "repository_name", t, "form", "multi")
		}
	}
	if r.repositoryVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "repository_version", r.repositoryVersion, "form", "")
	}
	if r.signed != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "signed", r.signed, "form", "")
	}
	if r.tags != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "tags", r.tags, "form", "")
	}
	if r.version != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "version", r.version, "form", "")
	}
	if r.versionRange != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "version_range", r.versionRange, "form", "")
	}
	if r.fields != nil {
		t := *r.fields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "fields", t, "form", "multi")
		}
	}
	if r.excludeFields != nil {
		t := *r.excludeFields
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
                               parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest struct {
	ctx context.Context
	ApiService *PluginSearchCollectionVersionsAPIService
	ansibleCrossRepositoryCollectionVersionIndexHref string
	collectionVersionSearchList *CollectionVersionSearchList
	xTaskDiagnostics *[]string
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest) CollectionVersionSearchList(collectionVersionSearchList CollectionVersionSearchList) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest {
	r.collectionVersionSearchList = &collectionVersionSearchList
	return r
}

// List of profilers to use on tasks.
func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest) XTaskDiagnostics(xTaskDiagnostics []string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest {
	r.xTaskDiagnostics = &xTaskDiagnostics
	return r
}

func (r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest) Execute() (*CollectionVersionSearchListResponse, *http.Response, error) {
	return r.ApiService.PluginAnsibleSearchCollectionVersionsRebuildExecute(r)
}

/*
PluginAnsibleSearchCollectionVersionsRebuild Method for PluginAnsibleSearchCollectionVersionsRebuild

A viewset for cross-repo searches.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param ansibleCrossRepositoryCollectionVersionIndexHref
 @return PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest
*/
func (a *PluginSearchCollectionVersionsAPIService) PluginAnsibleSearchCollectionVersionsRebuild(ctx context.Context, ansibleCrossRepositoryCollectionVersionIndexHref string) PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest {
	return PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest{
		ApiService: a,
		ctx: ctx,
		ansibleCrossRepositoryCollectionVersionIndexHref: ansibleCrossRepositoryCollectionVersionIndexHref,
	}
}

// Execute executes the request
//  @return CollectionVersionSearchListResponse
func (a *PluginSearchCollectionVersionsAPIService) PluginAnsibleSearchCollectionVersionsRebuildExecute(r PluginSearchCollectionVersionsAPIPluginAnsibleSearchCollectionVersionsRebuildRequest) (*CollectionVersionSearchListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CollectionVersionSearchListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PluginSearchCollectionVersionsAPIService.PluginAnsibleSearchCollectionVersionsRebuild")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/{ansible_cross_repository_collection_version_index_href}api/v3/plugin/ansible/search/collection-versions/"
	localVarPath = strings.Replace(localVarPath, "{"+"ansible_cross_repository_collection_version_index_href"+"}", url.PathEscape(parameterValueToString(r.ansibleCrossRepositoryCollectionVersionIndexHref, "ansibleCrossRepositoryCollectionVersionIndexHref")), -1)
        localVarPath = strings.Replace(localVarPath, "/%2F", "/", -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.collectionVersionSearchList == nil {
		return localVarReturnValue, nil, reportError("collectionVersionSearchList is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTaskDiagnostics != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Task-Diagnostics", r.xTaskDiagnostics, "simple", "csv")
	}
	// body params
	localVarPostBody = r.collectionVersionSearchList
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
