/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pulpbindings

import (
	"encoding/json"
	"fmt"
)

// checks if the NestedOpenPGPUserAttributeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedOpenPGPUserAttributeResponse{}

// NestedOpenPGPUserAttributeResponse Base serializer for use with [pulpcore.app.models.Model][]This ensures that all Serializers provide values for the 'pulp_href` field.The class provides a default for the ``ref_name`` attribute in theModelSerializers's ``Meta`` class. This ensures that the OpenAPI definitionsof plugins are namespaced properly.
type NestedOpenPGPUserAttributeResponse struct {
	Sha256 string `json:"sha256"`
	Signatures []NestedOpenPGPSignatureResponse `json:"signatures,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NestedOpenPGPUserAttributeResponse NestedOpenPGPUserAttributeResponse

// NewNestedOpenPGPUserAttributeResponse instantiates a new NestedOpenPGPUserAttributeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedOpenPGPUserAttributeResponse(sha256 string) *NestedOpenPGPUserAttributeResponse {
	this := NestedOpenPGPUserAttributeResponse{}
	this.Sha256 = sha256
	return &this
}

// NewNestedOpenPGPUserAttributeResponseWithDefaults instantiates a new NestedOpenPGPUserAttributeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedOpenPGPUserAttributeResponseWithDefaults() *NestedOpenPGPUserAttributeResponse {
	this := NestedOpenPGPUserAttributeResponse{}
	return &this
}

// GetSha256 returns the Sha256 field value
func (o *NestedOpenPGPUserAttributeResponse) GetSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value
// and a boolean to check if the value has been set.
func (o *NestedOpenPGPUserAttributeResponse) GetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sha256, true
}

// SetSha256 sets field value
func (o *NestedOpenPGPUserAttributeResponse) SetSha256(v string) {
	o.Sha256 = v
}

// GetSignatures returns the Signatures field value if set, zero value otherwise.
func (o *NestedOpenPGPUserAttributeResponse) GetSignatures() []NestedOpenPGPSignatureResponse {
	if o == nil || IsNil(o.Signatures) {
		var ret []NestedOpenPGPSignatureResponse
		return ret
	}
	return o.Signatures
}

// GetSignaturesOk returns a tuple with the Signatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedOpenPGPUserAttributeResponse) GetSignaturesOk() ([]NestedOpenPGPSignatureResponse, bool) {
	if o == nil || IsNil(o.Signatures) {
		return nil, false
	}
	return o.Signatures, true
}

// HasSignatures returns a boolean if a field has been set.
func (o *NestedOpenPGPUserAttributeResponse) HasSignatures() bool {
	if o != nil && !IsNil(o.Signatures) {
		return true
	}

	return false
}

// SetSignatures gets a reference to the given []NestedOpenPGPSignatureResponse and assigns it to the Signatures field.
func (o *NestedOpenPGPUserAttributeResponse) SetSignatures(v []NestedOpenPGPSignatureResponse) {
	o.Signatures = v
}

func (o NestedOpenPGPUserAttributeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedOpenPGPUserAttributeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sha256"] = o.Sha256
	if !IsNil(o.Signatures) {
		toSerialize["signatures"] = o.Signatures
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedOpenPGPUserAttributeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNestedOpenPGPUserAttributeResponse := _NestedOpenPGPUserAttributeResponse{}

	err = json.Unmarshal(data, &varNestedOpenPGPUserAttributeResponse)

	if err != nil {
		return err
	}

	*o = NestedOpenPGPUserAttributeResponse(varNestedOpenPGPUserAttributeResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "signatures")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedOpenPGPUserAttributeResponse struct {
	value *NestedOpenPGPUserAttributeResponse
	isSet bool
}

func (v NullableNestedOpenPGPUserAttributeResponse) Get() *NestedOpenPGPUserAttributeResponse {
	return v.value
}

func (v *NullableNestedOpenPGPUserAttributeResponse) Set(val *NestedOpenPGPUserAttributeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedOpenPGPUserAttributeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedOpenPGPUserAttributeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedOpenPGPUserAttributeResponse(val *NestedOpenPGPUserAttributeResponse) *NullableNestedOpenPGPUserAttributeResponse {
	return &NullableNestedOpenPGPUserAttributeResponse{value: val, isSet: true}
}

func (v NullableNestedOpenPGPUserAttributeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedOpenPGPUserAttributeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


