/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pulpbindings

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the DebSourcePackageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DebSourcePackageResponse{}

// DebSourcePackageResponse A Serializer for DscFile.
type DebSourcePackageResponse struct {
	PulpHref *string `json:"pulp_href,omitempty"`
	// The Pulp Resource Name (PRN).
	Prn *string `json:"prn,omitempty"`
	// Timestamp of creation.
	PulpCreated *time.Time `json:"pulp_created,omitempty"`
	// Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same.
	PulpLastUpdated *time.Time `json:"pulp_last_updated,omitempty"`
	// A dictionary of arbitrary key/value pairs used to describe a specific Content instance.
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	VulnReport *string `json:"vuln_report,omitempty"`
	// A dict mapping relative paths inside the Content to the correspondingArtifact URLs. E.g.: {'relative/path': '/artifacts/1/'
	Artifacts map[string]interface{} `json:"artifacts"`
	// Relative path of the Debian Source Control (dsc) file.It is normally advised to let Pulp generate this.
	RelativePath *string `json:"relative_path,omitempty"`
	// sha256 digest of the dsc file.
	Sha256 *string `json:"sha256,omitempty"`
	Format *string `json:"format,omitempty"`
	Source *string `json:"source,omitempty"`
	Binary *string `json:"binary,omitempty"`
	Architecture *string `json:"architecture,omitempty"`
	Version *string `json:"version,omitempty"`
	Maintainer *string `json:"maintainer,omitempty"`
	Uploaders *string `json:"uploaders,omitempty"`
	Homepage *string `json:"homepage,omitempty"`
	VcsBrowser *string `json:"vcs_browser,omitempty"`
	VcsArch *string `json:"vcs_arch,omitempty"`
	VcsBzr *string `json:"vcs_bzr,omitempty"`
	VcsCvs *string `json:"vcs_cvs,omitempty"`
	VcsDarcs *string `json:"vcs_darcs,omitempty"`
	VcsGit *string `json:"vcs_git,omitempty"`
	VcsHg *string `json:"vcs_hg,omitempty"`
	VcsMtn *string `json:"vcs_mtn,omitempty"`
	VcsSnv *string `json:"vcs_snv,omitempty"`
	Testsuite *string `json:"testsuite,omitempty"`
	Dgit *string `json:"dgit,omitempty"`
	StandardsVersion *string `json:"standards_version,omitempty"`
	BuildDepends *string `json:"build_depends,omitempty"`
	BuildDependsIndep *string `json:"build_depends_indep,omitempty"`
	BuildDependsArch *string `json:"build_depends_arch,omitempty"`
	BuildConflicts *string `json:"build_conflicts,omitempty"`
	BuildConflictsIndep *string `json:"build_conflicts_indep,omitempty"`
	BuildConflictsArch *string `json:"build_conflicts_arch,omitempty"`
	PackageList *string `json:"package_list,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DebSourcePackageResponse DebSourcePackageResponse

// NewDebSourcePackageResponse instantiates a new DebSourcePackageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDebSourcePackageResponse(artifacts map[string]interface{}) *DebSourcePackageResponse {
	this := DebSourcePackageResponse{}
	this.Artifacts = artifacts
	return &this
}

// NewDebSourcePackageResponseWithDefaults instantiates a new DebSourcePackageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDebSourcePackageResponseWithDefaults() *DebSourcePackageResponse {
	this := DebSourcePackageResponse{}
	return &this
}

// GetPulpHref returns the PulpHref field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetPulpHref() string {
	if o == nil || IsNil(o.PulpHref) {
		var ret string
		return ret
	}
	return *o.PulpHref
}

// GetPulpHrefOk returns a tuple with the PulpHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetPulpHrefOk() (*string, bool) {
	if o == nil || IsNil(o.PulpHref) {
		return nil, false
	}
	return o.PulpHref, true
}

// HasPulpHref returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasPulpHref() bool {
	if o != nil && !IsNil(o.PulpHref) {
		return true
	}

	return false
}

// SetPulpHref gets a reference to the given string and assigns it to the PulpHref field.
func (o *DebSourcePackageResponse) SetPulpHref(v string) {
	o.PulpHref = &v
}

// GetPrn returns the Prn field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetPrn() string {
	if o == nil || IsNil(o.Prn) {
		var ret string
		return ret
	}
	return *o.Prn
}

// GetPrnOk returns a tuple with the Prn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetPrnOk() (*string, bool) {
	if o == nil || IsNil(o.Prn) {
		return nil, false
	}
	return o.Prn, true
}

// HasPrn returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasPrn() bool {
	if o != nil && !IsNil(o.Prn) {
		return true
	}

	return false
}

// SetPrn gets a reference to the given string and assigns it to the Prn field.
func (o *DebSourcePackageResponse) SetPrn(v string) {
	o.Prn = &v
}

// GetPulpCreated returns the PulpCreated field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetPulpCreated() time.Time {
	if o == nil || IsNil(o.PulpCreated) {
		var ret time.Time
		return ret
	}
	return *o.PulpCreated
}

// GetPulpCreatedOk returns a tuple with the PulpCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetPulpCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpCreated) {
		return nil, false
	}
	return o.PulpCreated, true
}

// HasPulpCreated returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasPulpCreated() bool {
	if o != nil && !IsNil(o.PulpCreated) {
		return true
	}

	return false
}

// SetPulpCreated gets a reference to the given time.Time and assigns it to the PulpCreated field.
func (o *DebSourcePackageResponse) SetPulpCreated(v time.Time) {
	o.PulpCreated = &v
}

// GetPulpLastUpdated returns the PulpLastUpdated field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetPulpLastUpdated() time.Time {
	if o == nil || IsNil(o.PulpLastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.PulpLastUpdated
}

// GetPulpLastUpdatedOk returns a tuple with the PulpLastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetPulpLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PulpLastUpdated) {
		return nil, false
	}
	return o.PulpLastUpdated, true
}

// HasPulpLastUpdated returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasPulpLastUpdated() bool {
	if o != nil && !IsNil(o.PulpLastUpdated) {
		return true
	}

	return false
}

// SetPulpLastUpdated gets a reference to the given time.Time and assigns it to the PulpLastUpdated field.
func (o *DebSourcePackageResponse) SetPulpLastUpdated(v time.Time) {
	o.PulpLastUpdated = &v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *DebSourcePackageResponse) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetVulnReport returns the VulnReport field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVulnReport() string {
	if o == nil || IsNil(o.VulnReport) {
		var ret string
		return ret
	}
	return *o.VulnReport
}

// GetVulnReportOk returns a tuple with the VulnReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVulnReportOk() (*string, bool) {
	if o == nil || IsNil(o.VulnReport) {
		return nil, false
	}
	return o.VulnReport, true
}

// HasVulnReport returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVulnReport() bool {
	if o != nil && !IsNil(o.VulnReport) {
		return true
	}

	return false
}

// SetVulnReport gets a reference to the given string and assigns it to the VulnReport field.
func (o *DebSourcePackageResponse) SetVulnReport(v string) {
	o.VulnReport = &v
}

// GetArtifacts returns the Artifacts field value
func (o *DebSourcePackageResponse) GetArtifacts() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetArtifactsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Artifacts, true
}

// SetArtifacts sets field value
func (o *DebSourcePackageResponse) SetArtifacts(v map[string]interface{}) {
	o.Artifacts = v
}

// GetRelativePath returns the RelativePath field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetRelativePath() string {
	if o == nil || IsNil(o.RelativePath) {
		var ret string
		return ret
	}
	return *o.RelativePath
}

// GetRelativePathOk returns a tuple with the RelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetRelativePathOk() (*string, bool) {
	if o == nil || IsNil(o.RelativePath) {
		return nil, false
	}
	return o.RelativePath, true
}

// HasRelativePath returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasRelativePath() bool {
	if o != nil && !IsNil(o.RelativePath) {
		return true
	}

	return false
}

// SetRelativePath gets a reference to the given string and assigns it to the RelativePath field.
func (o *DebSourcePackageResponse) SetRelativePath(v string) {
	o.RelativePath = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *DebSourcePackageResponse) SetSha256(v string) {
	o.Sha256 = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *DebSourcePackageResponse) SetFormat(v string) {
	o.Format = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *DebSourcePackageResponse) SetSource(v string) {
	o.Source = &v
}

// GetBinary returns the Binary field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBinary() string {
	if o == nil || IsNil(o.Binary) {
		var ret string
		return ret
	}
	return *o.Binary
}

// GetBinaryOk returns a tuple with the Binary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBinaryOk() (*string, bool) {
	if o == nil || IsNil(o.Binary) {
		return nil, false
	}
	return o.Binary, true
}

// HasBinary returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBinary() bool {
	if o != nil && !IsNil(o.Binary) {
		return true
	}

	return false
}

// SetBinary gets a reference to the given string and assigns it to the Binary field.
func (o *DebSourcePackageResponse) SetBinary(v string) {
	o.Binary = &v
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetArchitecture() string {
	if o == nil || IsNil(o.Architecture) {
		var ret string
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetArchitectureOk() (*string, bool) {
	if o == nil || IsNil(o.Architecture) {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasArchitecture() bool {
	if o != nil && !IsNil(o.Architecture) {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given string and assigns it to the Architecture field.
func (o *DebSourcePackageResponse) SetArchitecture(v string) {
	o.Architecture = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *DebSourcePackageResponse) SetVersion(v string) {
	o.Version = &v
}

// GetMaintainer returns the Maintainer field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetMaintainer() string {
	if o == nil || IsNil(o.Maintainer) {
		var ret string
		return ret
	}
	return *o.Maintainer
}

// GetMaintainerOk returns a tuple with the Maintainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetMaintainerOk() (*string, bool) {
	if o == nil || IsNil(o.Maintainer) {
		return nil, false
	}
	return o.Maintainer, true
}

// HasMaintainer returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasMaintainer() bool {
	if o != nil && !IsNil(o.Maintainer) {
		return true
	}

	return false
}

// SetMaintainer gets a reference to the given string and assigns it to the Maintainer field.
func (o *DebSourcePackageResponse) SetMaintainer(v string) {
	o.Maintainer = &v
}

// GetUploaders returns the Uploaders field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetUploaders() string {
	if o == nil || IsNil(o.Uploaders) {
		var ret string
		return ret
	}
	return *o.Uploaders
}

// GetUploadersOk returns a tuple with the Uploaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetUploadersOk() (*string, bool) {
	if o == nil || IsNil(o.Uploaders) {
		return nil, false
	}
	return o.Uploaders, true
}

// HasUploaders returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasUploaders() bool {
	if o != nil && !IsNil(o.Uploaders) {
		return true
	}

	return false
}

// SetUploaders gets a reference to the given string and assigns it to the Uploaders field.
func (o *DebSourcePackageResponse) SetUploaders(v string) {
	o.Uploaders = &v
}

// GetHomepage returns the Homepage field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetHomepage() string {
	if o == nil || IsNil(o.Homepage) {
		var ret string
		return ret
	}
	return *o.Homepage
}

// GetHomepageOk returns a tuple with the Homepage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetHomepageOk() (*string, bool) {
	if o == nil || IsNil(o.Homepage) {
		return nil, false
	}
	return o.Homepage, true
}

// HasHomepage returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasHomepage() bool {
	if o != nil && !IsNil(o.Homepage) {
		return true
	}

	return false
}

// SetHomepage gets a reference to the given string and assigns it to the Homepage field.
func (o *DebSourcePackageResponse) SetHomepage(v string) {
	o.Homepage = &v
}

// GetVcsBrowser returns the VcsBrowser field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsBrowser() string {
	if o == nil || IsNil(o.VcsBrowser) {
		var ret string
		return ret
	}
	return *o.VcsBrowser
}

// GetVcsBrowserOk returns a tuple with the VcsBrowser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsBrowserOk() (*string, bool) {
	if o == nil || IsNil(o.VcsBrowser) {
		return nil, false
	}
	return o.VcsBrowser, true
}

// HasVcsBrowser returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsBrowser() bool {
	if o != nil && !IsNil(o.VcsBrowser) {
		return true
	}

	return false
}

// SetVcsBrowser gets a reference to the given string and assigns it to the VcsBrowser field.
func (o *DebSourcePackageResponse) SetVcsBrowser(v string) {
	o.VcsBrowser = &v
}

// GetVcsArch returns the VcsArch field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsArch() string {
	if o == nil || IsNil(o.VcsArch) {
		var ret string
		return ret
	}
	return *o.VcsArch
}

// GetVcsArchOk returns a tuple with the VcsArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsArchOk() (*string, bool) {
	if o == nil || IsNil(o.VcsArch) {
		return nil, false
	}
	return o.VcsArch, true
}

// HasVcsArch returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsArch() bool {
	if o != nil && !IsNil(o.VcsArch) {
		return true
	}

	return false
}

// SetVcsArch gets a reference to the given string and assigns it to the VcsArch field.
func (o *DebSourcePackageResponse) SetVcsArch(v string) {
	o.VcsArch = &v
}

// GetVcsBzr returns the VcsBzr field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsBzr() string {
	if o == nil || IsNil(o.VcsBzr) {
		var ret string
		return ret
	}
	return *o.VcsBzr
}

// GetVcsBzrOk returns a tuple with the VcsBzr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsBzrOk() (*string, bool) {
	if o == nil || IsNil(o.VcsBzr) {
		return nil, false
	}
	return o.VcsBzr, true
}

// HasVcsBzr returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsBzr() bool {
	if o != nil && !IsNil(o.VcsBzr) {
		return true
	}

	return false
}

// SetVcsBzr gets a reference to the given string and assigns it to the VcsBzr field.
func (o *DebSourcePackageResponse) SetVcsBzr(v string) {
	o.VcsBzr = &v
}

// GetVcsCvs returns the VcsCvs field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsCvs() string {
	if o == nil || IsNil(o.VcsCvs) {
		var ret string
		return ret
	}
	return *o.VcsCvs
}

// GetVcsCvsOk returns a tuple with the VcsCvs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsCvsOk() (*string, bool) {
	if o == nil || IsNil(o.VcsCvs) {
		return nil, false
	}
	return o.VcsCvs, true
}

// HasVcsCvs returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsCvs() bool {
	if o != nil && !IsNil(o.VcsCvs) {
		return true
	}

	return false
}

// SetVcsCvs gets a reference to the given string and assigns it to the VcsCvs field.
func (o *DebSourcePackageResponse) SetVcsCvs(v string) {
	o.VcsCvs = &v
}

// GetVcsDarcs returns the VcsDarcs field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsDarcs() string {
	if o == nil || IsNil(o.VcsDarcs) {
		var ret string
		return ret
	}
	return *o.VcsDarcs
}

// GetVcsDarcsOk returns a tuple with the VcsDarcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsDarcsOk() (*string, bool) {
	if o == nil || IsNil(o.VcsDarcs) {
		return nil, false
	}
	return o.VcsDarcs, true
}

// HasVcsDarcs returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsDarcs() bool {
	if o != nil && !IsNil(o.VcsDarcs) {
		return true
	}

	return false
}

// SetVcsDarcs gets a reference to the given string and assigns it to the VcsDarcs field.
func (o *DebSourcePackageResponse) SetVcsDarcs(v string) {
	o.VcsDarcs = &v
}

// GetVcsGit returns the VcsGit field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsGit() string {
	if o == nil || IsNil(o.VcsGit) {
		var ret string
		return ret
	}
	return *o.VcsGit
}

// GetVcsGitOk returns a tuple with the VcsGit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsGitOk() (*string, bool) {
	if o == nil || IsNil(o.VcsGit) {
		return nil, false
	}
	return o.VcsGit, true
}

// HasVcsGit returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsGit() bool {
	if o != nil && !IsNil(o.VcsGit) {
		return true
	}

	return false
}

// SetVcsGit gets a reference to the given string and assigns it to the VcsGit field.
func (o *DebSourcePackageResponse) SetVcsGit(v string) {
	o.VcsGit = &v
}

// GetVcsHg returns the VcsHg field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsHg() string {
	if o == nil || IsNil(o.VcsHg) {
		var ret string
		return ret
	}
	return *o.VcsHg
}

// GetVcsHgOk returns a tuple with the VcsHg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsHgOk() (*string, bool) {
	if o == nil || IsNil(o.VcsHg) {
		return nil, false
	}
	return o.VcsHg, true
}

// HasVcsHg returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsHg() bool {
	if o != nil && !IsNil(o.VcsHg) {
		return true
	}

	return false
}

// SetVcsHg gets a reference to the given string and assigns it to the VcsHg field.
func (o *DebSourcePackageResponse) SetVcsHg(v string) {
	o.VcsHg = &v
}

// GetVcsMtn returns the VcsMtn field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsMtn() string {
	if o == nil || IsNil(o.VcsMtn) {
		var ret string
		return ret
	}
	return *o.VcsMtn
}

// GetVcsMtnOk returns a tuple with the VcsMtn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsMtnOk() (*string, bool) {
	if o == nil || IsNil(o.VcsMtn) {
		return nil, false
	}
	return o.VcsMtn, true
}

// HasVcsMtn returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsMtn() bool {
	if o != nil && !IsNil(o.VcsMtn) {
		return true
	}

	return false
}

// SetVcsMtn gets a reference to the given string and assigns it to the VcsMtn field.
func (o *DebSourcePackageResponse) SetVcsMtn(v string) {
	o.VcsMtn = &v
}

// GetVcsSnv returns the VcsSnv field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetVcsSnv() string {
	if o == nil || IsNil(o.VcsSnv) {
		var ret string
		return ret
	}
	return *o.VcsSnv
}

// GetVcsSnvOk returns a tuple with the VcsSnv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetVcsSnvOk() (*string, bool) {
	if o == nil || IsNil(o.VcsSnv) {
		return nil, false
	}
	return o.VcsSnv, true
}

// HasVcsSnv returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasVcsSnv() bool {
	if o != nil && !IsNil(o.VcsSnv) {
		return true
	}

	return false
}

// SetVcsSnv gets a reference to the given string and assigns it to the VcsSnv field.
func (o *DebSourcePackageResponse) SetVcsSnv(v string) {
	o.VcsSnv = &v
}

// GetTestsuite returns the Testsuite field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetTestsuite() string {
	if o == nil || IsNil(o.Testsuite) {
		var ret string
		return ret
	}
	return *o.Testsuite
}

// GetTestsuiteOk returns a tuple with the Testsuite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetTestsuiteOk() (*string, bool) {
	if o == nil || IsNil(o.Testsuite) {
		return nil, false
	}
	return o.Testsuite, true
}

// HasTestsuite returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasTestsuite() bool {
	if o != nil && !IsNil(o.Testsuite) {
		return true
	}

	return false
}

// SetTestsuite gets a reference to the given string and assigns it to the Testsuite field.
func (o *DebSourcePackageResponse) SetTestsuite(v string) {
	o.Testsuite = &v
}

// GetDgit returns the Dgit field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetDgit() string {
	if o == nil || IsNil(o.Dgit) {
		var ret string
		return ret
	}
	return *o.Dgit
}

// GetDgitOk returns a tuple with the Dgit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetDgitOk() (*string, bool) {
	if o == nil || IsNil(o.Dgit) {
		return nil, false
	}
	return o.Dgit, true
}

// HasDgit returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasDgit() bool {
	if o != nil && !IsNil(o.Dgit) {
		return true
	}

	return false
}

// SetDgit gets a reference to the given string and assigns it to the Dgit field.
func (o *DebSourcePackageResponse) SetDgit(v string) {
	o.Dgit = &v
}

// GetStandardsVersion returns the StandardsVersion field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetStandardsVersion() string {
	if o == nil || IsNil(o.StandardsVersion) {
		var ret string
		return ret
	}
	return *o.StandardsVersion
}

// GetStandardsVersionOk returns a tuple with the StandardsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetStandardsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.StandardsVersion) {
		return nil, false
	}
	return o.StandardsVersion, true
}

// HasStandardsVersion returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasStandardsVersion() bool {
	if o != nil && !IsNil(o.StandardsVersion) {
		return true
	}

	return false
}

// SetStandardsVersion gets a reference to the given string and assigns it to the StandardsVersion field.
func (o *DebSourcePackageResponse) SetStandardsVersion(v string) {
	o.StandardsVersion = &v
}

// GetBuildDepends returns the BuildDepends field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBuildDepends() string {
	if o == nil || IsNil(o.BuildDepends) {
		var ret string
		return ret
	}
	return *o.BuildDepends
}

// GetBuildDependsOk returns a tuple with the BuildDepends field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBuildDependsOk() (*string, bool) {
	if o == nil || IsNil(o.BuildDepends) {
		return nil, false
	}
	return o.BuildDepends, true
}

// HasBuildDepends returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBuildDepends() bool {
	if o != nil && !IsNil(o.BuildDepends) {
		return true
	}

	return false
}

// SetBuildDepends gets a reference to the given string and assigns it to the BuildDepends field.
func (o *DebSourcePackageResponse) SetBuildDepends(v string) {
	o.BuildDepends = &v
}

// GetBuildDependsIndep returns the BuildDependsIndep field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBuildDependsIndep() string {
	if o == nil || IsNil(o.BuildDependsIndep) {
		var ret string
		return ret
	}
	return *o.BuildDependsIndep
}

// GetBuildDependsIndepOk returns a tuple with the BuildDependsIndep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBuildDependsIndepOk() (*string, bool) {
	if o == nil || IsNil(o.BuildDependsIndep) {
		return nil, false
	}
	return o.BuildDependsIndep, true
}

// HasBuildDependsIndep returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBuildDependsIndep() bool {
	if o != nil && !IsNil(o.BuildDependsIndep) {
		return true
	}

	return false
}

// SetBuildDependsIndep gets a reference to the given string and assigns it to the BuildDependsIndep field.
func (o *DebSourcePackageResponse) SetBuildDependsIndep(v string) {
	o.BuildDependsIndep = &v
}

// GetBuildDependsArch returns the BuildDependsArch field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBuildDependsArch() string {
	if o == nil || IsNil(o.BuildDependsArch) {
		var ret string
		return ret
	}
	return *o.BuildDependsArch
}

// GetBuildDependsArchOk returns a tuple with the BuildDependsArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBuildDependsArchOk() (*string, bool) {
	if o == nil || IsNil(o.BuildDependsArch) {
		return nil, false
	}
	return o.BuildDependsArch, true
}

// HasBuildDependsArch returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBuildDependsArch() bool {
	if o != nil && !IsNil(o.BuildDependsArch) {
		return true
	}

	return false
}

// SetBuildDependsArch gets a reference to the given string and assigns it to the BuildDependsArch field.
func (o *DebSourcePackageResponse) SetBuildDependsArch(v string) {
	o.BuildDependsArch = &v
}

// GetBuildConflicts returns the BuildConflicts field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBuildConflicts() string {
	if o == nil || IsNil(o.BuildConflicts) {
		var ret string
		return ret
	}
	return *o.BuildConflicts
}

// GetBuildConflictsOk returns a tuple with the BuildConflicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBuildConflictsOk() (*string, bool) {
	if o == nil || IsNil(o.BuildConflicts) {
		return nil, false
	}
	return o.BuildConflicts, true
}

// HasBuildConflicts returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBuildConflicts() bool {
	if o != nil && !IsNil(o.BuildConflicts) {
		return true
	}

	return false
}

// SetBuildConflicts gets a reference to the given string and assigns it to the BuildConflicts field.
func (o *DebSourcePackageResponse) SetBuildConflicts(v string) {
	o.BuildConflicts = &v
}

// GetBuildConflictsIndep returns the BuildConflictsIndep field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBuildConflictsIndep() string {
	if o == nil || IsNil(o.BuildConflictsIndep) {
		var ret string
		return ret
	}
	return *o.BuildConflictsIndep
}

// GetBuildConflictsIndepOk returns a tuple with the BuildConflictsIndep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBuildConflictsIndepOk() (*string, bool) {
	if o == nil || IsNil(o.BuildConflictsIndep) {
		return nil, false
	}
	return o.BuildConflictsIndep, true
}

// HasBuildConflictsIndep returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBuildConflictsIndep() bool {
	if o != nil && !IsNil(o.BuildConflictsIndep) {
		return true
	}

	return false
}

// SetBuildConflictsIndep gets a reference to the given string and assigns it to the BuildConflictsIndep field.
func (o *DebSourcePackageResponse) SetBuildConflictsIndep(v string) {
	o.BuildConflictsIndep = &v
}

// GetBuildConflictsArch returns the BuildConflictsArch field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetBuildConflictsArch() string {
	if o == nil || IsNil(o.BuildConflictsArch) {
		var ret string
		return ret
	}
	return *o.BuildConflictsArch
}

// GetBuildConflictsArchOk returns a tuple with the BuildConflictsArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetBuildConflictsArchOk() (*string, bool) {
	if o == nil || IsNil(o.BuildConflictsArch) {
		return nil, false
	}
	return o.BuildConflictsArch, true
}

// HasBuildConflictsArch returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasBuildConflictsArch() bool {
	if o != nil && !IsNil(o.BuildConflictsArch) {
		return true
	}

	return false
}

// SetBuildConflictsArch gets a reference to the given string and assigns it to the BuildConflictsArch field.
func (o *DebSourcePackageResponse) SetBuildConflictsArch(v string) {
	o.BuildConflictsArch = &v
}

// GetPackageList returns the PackageList field value if set, zero value otherwise.
func (o *DebSourcePackageResponse) GetPackageList() string {
	if o == nil || IsNil(o.PackageList) {
		var ret string
		return ret
	}
	return *o.PackageList
}

// GetPackageListOk returns a tuple with the PackageList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DebSourcePackageResponse) GetPackageListOk() (*string, bool) {
	if o == nil || IsNil(o.PackageList) {
		return nil, false
	}
	return o.PackageList, true
}

// HasPackageList returns a boolean if a field has been set.
func (o *DebSourcePackageResponse) HasPackageList() bool {
	if o != nil && !IsNil(o.PackageList) {
		return true
	}

	return false
}

// SetPackageList gets a reference to the given string and assigns it to the PackageList field.
func (o *DebSourcePackageResponse) SetPackageList(v string) {
	o.PackageList = &v
}

func (o DebSourcePackageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DebSourcePackageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PulpHref) {
		toSerialize["pulp_href"] = o.PulpHref
	}
	if !IsNil(o.Prn) {
		toSerialize["prn"] = o.Prn
	}
	if !IsNil(o.PulpCreated) {
		toSerialize["pulp_created"] = o.PulpCreated
	}
	if !IsNil(o.PulpLastUpdated) {
		toSerialize["pulp_last_updated"] = o.PulpLastUpdated
	}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.VulnReport) {
		toSerialize["vuln_report"] = o.VulnReport
	}
	toSerialize["artifacts"] = o.Artifacts
	if !IsNil(o.RelativePath) {
		toSerialize["relative_path"] = o.RelativePath
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Binary) {
		toSerialize["binary"] = o.Binary
	}
	if !IsNil(o.Architecture) {
		toSerialize["architecture"] = o.Architecture
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Maintainer) {
		toSerialize["maintainer"] = o.Maintainer
	}
	if !IsNil(o.Uploaders) {
		toSerialize["uploaders"] = o.Uploaders
	}
	if !IsNil(o.Homepage) {
		toSerialize["homepage"] = o.Homepage
	}
	if !IsNil(o.VcsBrowser) {
		toSerialize["vcs_browser"] = o.VcsBrowser
	}
	if !IsNil(o.VcsArch) {
		toSerialize["vcs_arch"] = o.VcsArch
	}
	if !IsNil(o.VcsBzr) {
		toSerialize["vcs_bzr"] = o.VcsBzr
	}
	if !IsNil(o.VcsCvs) {
		toSerialize["vcs_cvs"] = o.VcsCvs
	}
	if !IsNil(o.VcsDarcs) {
		toSerialize["vcs_darcs"] = o.VcsDarcs
	}
	if !IsNil(o.VcsGit) {
		toSerialize["vcs_git"] = o.VcsGit
	}
	if !IsNil(o.VcsHg) {
		toSerialize["vcs_hg"] = o.VcsHg
	}
	if !IsNil(o.VcsMtn) {
		toSerialize["vcs_mtn"] = o.VcsMtn
	}
	if !IsNil(o.VcsSnv) {
		toSerialize["vcs_snv"] = o.VcsSnv
	}
	if !IsNil(o.Testsuite) {
		toSerialize["testsuite"] = o.Testsuite
	}
	if !IsNil(o.Dgit) {
		toSerialize["dgit"] = o.Dgit
	}
	if !IsNil(o.StandardsVersion) {
		toSerialize["standards_version"] = o.StandardsVersion
	}
	if !IsNil(o.BuildDepends) {
		toSerialize["build_depends"] = o.BuildDepends
	}
	if !IsNil(o.BuildDependsIndep) {
		toSerialize["build_depends_indep"] = o.BuildDependsIndep
	}
	if !IsNil(o.BuildDependsArch) {
		toSerialize["build_depends_arch"] = o.BuildDependsArch
	}
	if !IsNil(o.BuildConflicts) {
		toSerialize["build_conflicts"] = o.BuildConflicts
	}
	if !IsNil(o.BuildConflictsIndep) {
		toSerialize["build_conflicts_indep"] = o.BuildConflictsIndep
	}
	if !IsNil(o.BuildConflictsArch) {
		toSerialize["build_conflicts_arch"] = o.BuildConflictsArch
	}
	if !IsNil(o.PackageList) {
		toSerialize["package_list"] = o.PackageList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DebSourcePackageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"artifacts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDebSourcePackageResponse := _DebSourcePackageResponse{}

	err = json.Unmarshal(data, &varDebSourcePackageResponse)

	if err != nil {
		return err
	}

	*o = DebSourcePackageResponse(varDebSourcePackageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pulp_href")
		delete(additionalProperties, "prn")
		delete(additionalProperties, "pulp_created")
		delete(additionalProperties, "pulp_last_updated")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "vuln_report")
		delete(additionalProperties, "artifacts")
		delete(additionalProperties, "relative_path")
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "format")
		delete(additionalProperties, "source")
		delete(additionalProperties, "binary")
		delete(additionalProperties, "architecture")
		delete(additionalProperties, "version")
		delete(additionalProperties, "maintainer")
		delete(additionalProperties, "uploaders")
		delete(additionalProperties, "homepage")
		delete(additionalProperties, "vcs_browser")
		delete(additionalProperties, "vcs_arch")
		delete(additionalProperties, "vcs_bzr")
		delete(additionalProperties, "vcs_cvs")
		delete(additionalProperties, "vcs_darcs")
		delete(additionalProperties, "vcs_git")
		delete(additionalProperties, "vcs_hg")
		delete(additionalProperties, "vcs_mtn")
		delete(additionalProperties, "vcs_snv")
		delete(additionalProperties, "testsuite")
		delete(additionalProperties, "dgit")
		delete(additionalProperties, "standards_version")
		delete(additionalProperties, "build_depends")
		delete(additionalProperties, "build_depends_indep")
		delete(additionalProperties, "build_depends_arch")
		delete(additionalProperties, "build_conflicts")
		delete(additionalProperties, "build_conflicts_indep")
		delete(additionalProperties, "build_conflicts_arch")
		delete(additionalProperties, "package_list")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDebSourcePackageResponse struct {
	value *DebSourcePackageResponse
	isSet bool
}

func (v NullableDebSourcePackageResponse) Get() *DebSourcePackageResponse {
	return v.value
}

func (v *NullableDebSourcePackageResponse) Set(val *DebSourcePackageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDebSourcePackageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDebSourcePackageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDebSourcePackageResponse(val *DebSourcePackageResponse) *NullableDebSourcePackageResponse {
	return &NullableDebSourcePackageResponse{value: val, isSet: true}
}

func (v NullableDebSourcePackageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDebSourcePackageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


