/*
Pulp 3 API

Fetch, Upload, Organize, and Distribute Software Packages

API version: v3
Contact: pulp-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pulpbindings

import (
	"encoding/json"
	"os"
	"fmt"
)

// checks if the AnsibleCollectionVersionSignature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnsibleCollectionVersionSignature{}

// AnsibleCollectionVersionSignature A serializer for signature models.
type AnsibleCollectionVersionSignature struct {
	// A URI of a repository the new content unit should be associated with.
	Repository *string `json:"repository,omitempty"`
	// A dictionary of arbitrary key/value pairs used to describe a specific Content instance.
	PulpLabels *map[string]string `json:"pulp_labels,omitempty"`
	// An uploaded file that may be turned into the content unit.
	File **os.File `json:"file,omitempty"`
	// An uncommitted upload that may be turned into the content unit.
	Upload *string `json:"upload,omitempty"`
	// A url that Pulp can download and turn into the content unit.
	FileUrl *string `json:"file_url,omitempty"`
	// The content this signature is pointing to.
	SignedCollection string `json:"signed_collection"`
	AdditionalProperties map[string]interface{}
}

type _AnsibleCollectionVersionSignature AnsibleCollectionVersionSignature

// NewAnsibleCollectionVersionSignature instantiates a new AnsibleCollectionVersionSignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnsibleCollectionVersionSignature(signedCollection string) *AnsibleCollectionVersionSignature {
	this := AnsibleCollectionVersionSignature{}
	this.SignedCollection = signedCollection
	return &this
}

// NewAnsibleCollectionVersionSignatureWithDefaults instantiates a new AnsibleCollectionVersionSignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnsibleCollectionVersionSignatureWithDefaults() *AnsibleCollectionVersionSignature {
	this := AnsibleCollectionVersionSignature{}
	return &this
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *AnsibleCollectionVersionSignature) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnsibleCollectionVersionSignature) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *AnsibleCollectionVersionSignature) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *AnsibleCollectionVersionSignature) SetRepository(v string) {
	o.Repository = &v
}

// GetPulpLabels returns the PulpLabels field value if set, zero value otherwise.
func (o *AnsibleCollectionVersionSignature) GetPulpLabels() map[string]string {
	if o == nil || IsNil(o.PulpLabels) {
		var ret map[string]string
		return ret
	}
	return *o.PulpLabels
}

// GetPulpLabelsOk returns a tuple with the PulpLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnsibleCollectionVersionSignature) GetPulpLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PulpLabels) {
		return nil, false
	}
	return o.PulpLabels, true
}

// HasPulpLabels returns a boolean if a field has been set.
func (o *AnsibleCollectionVersionSignature) HasPulpLabels() bool {
	if o != nil && !IsNil(o.PulpLabels) {
		return true
	}

	return false
}

// SetPulpLabels gets a reference to the given map[string]string and assigns it to the PulpLabels field.
func (o *AnsibleCollectionVersionSignature) SetPulpLabels(v map[string]string) {
	o.PulpLabels = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *AnsibleCollectionVersionSignature) GetFile() *os.File {
	if o == nil || IsNil(o.File) {
		var ret *os.File
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnsibleCollectionVersionSignature) GetFileOk() (**os.File, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *AnsibleCollectionVersionSignature) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given *os.File and assigns it to the File field.
func (o *AnsibleCollectionVersionSignature) SetFile(v *os.File) {
	o.File = &v
}

// GetUpload returns the Upload field value if set, zero value otherwise.
func (o *AnsibleCollectionVersionSignature) GetUpload() string {
	if o == nil || IsNil(o.Upload) {
		var ret string
		return ret
	}
	return *o.Upload
}

// GetUploadOk returns a tuple with the Upload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnsibleCollectionVersionSignature) GetUploadOk() (*string, bool) {
	if o == nil || IsNil(o.Upload) {
		return nil, false
	}
	return o.Upload, true
}

// HasUpload returns a boolean if a field has been set.
func (o *AnsibleCollectionVersionSignature) HasUpload() bool {
	if o != nil && !IsNil(o.Upload) {
		return true
	}

	return false
}

// SetUpload gets a reference to the given string and assigns it to the Upload field.
func (o *AnsibleCollectionVersionSignature) SetUpload(v string) {
	o.Upload = &v
}

// GetFileUrl returns the FileUrl field value if set, zero value otherwise.
func (o *AnsibleCollectionVersionSignature) GetFileUrl() string {
	if o == nil || IsNil(o.FileUrl) {
		var ret string
		return ret
	}
	return *o.FileUrl
}

// GetFileUrlOk returns a tuple with the FileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnsibleCollectionVersionSignature) GetFileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FileUrl) {
		return nil, false
	}
	return o.FileUrl, true
}

// HasFileUrl returns a boolean if a field has been set.
func (o *AnsibleCollectionVersionSignature) HasFileUrl() bool {
	if o != nil && !IsNil(o.FileUrl) {
		return true
	}

	return false
}

// SetFileUrl gets a reference to the given string and assigns it to the FileUrl field.
func (o *AnsibleCollectionVersionSignature) SetFileUrl(v string) {
	o.FileUrl = &v
}

// GetSignedCollection returns the SignedCollection field value
func (o *AnsibleCollectionVersionSignature) GetSignedCollection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedCollection
}

// GetSignedCollectionOk returns a tuple with the SignedCollection field value
// and a boolean to check if the value has been set.
func (o *AnsibleCollectionVersionSignature) GetSignedCollectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedCollection, true
}

// SetSignedCollection sets field value
func (o *AnsibleCollectionVersionSignature) SetSignedCollection(v string) {
	o.SignedCollection = v
}

func (o AnsibleCollectionVersionSignature) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnsibleCollectionVersionSignature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.PulpLabels) {
		toSerialize["pulp_labels"] = o.PulpLabels
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Upload) {
		toSerialize["upload"] = o.Upload
	}
	if !IsNil(o.FileUrl) {
		toSerialize["file_url"] = o.FileUrl
	}
	toSerialize["signed_collection"] = o.SignedCollection

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnsibleCollectionVersionSignature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signed_collection",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnsibleCollectionVersionSignature := _AnsibleCollectionVersionSignature{}

	err = json.Unmarshal(data, &varAnsibleCollectionVersionSignature)

	if err != nil {
		return err
	}

	*o = AnsibleCollectionVersionSignature(varAnsibleCollectionVersionSignature)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "repository")
		delete(additionalProperties, "pulp_labels")
		delete(additionalProperties, "file")
		delete(additionalProperties, "upload")
		delete(additionalProperties, "file_url")
		delete(additionalProperties, "signed_collection")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnsibleCollectionVersionSignature struct {
	value *AnsibleCollectionVersionSignature
	isSet bool
}

func (v NullableAnsibleCollectionVersionSignature) Get() *AnsibleCollectionVersionSignature {
	return v.value
}

func (v *NullableAnsibleCollectionVersionSignature) Set(val *AnsibleCollectionVersionSignature) {
	v.value = val
	v.isSet = true
}

func (v NullableAnsibleCollectionVersionSignature) IsSet() bool {
	return v.isSet
}

func (v *NullableAnsibleCollectionVersionSignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnsibleCollectionVersionSignature(val *AnsibleCollectionVersionSignature) *NullableAnsibleCollectionVersionSignature {
	return &NullableAnsibleCollectionVersionSignature{value: val, isSet: true}
}

func (v NullableAnsibleCollectionVersionSignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnsibleCollectionVersionSignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


