name: "Components CI"
on:
  workflow_call:

jobs:
  components:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - COMPONENT_TYPE: ingress
          - COMPONENT_TYPE: nodeport
          - COMPONENT_TYPE: telemetry
          - COMPONENT_TYPE: ldap
          - COMPONENT_TYPE: external-db
          - COMPONENT_TYPE: s3
          - COMPONENT_TYPE: azure
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
          echo "TEST=pulp" >> $GITHUB_ENV
          echo "COMPONENT_TYPE=${{ matrix.COMPONENT_TYPE }}" >> $GITHUB_ENV
        shell: bash
      - name: Updating registries configuration
        run: |
          if [ -f "/etc/docker/daemon.json" ] || sudo systemctl is-active --quiet docker
          then
            echo "INFO:
            Updating docker configuration
            "

            echo "$(cat /etc/docker/daemon.json | jq -s '.[0] + {
            "insecure-registries" : ["ingress.local","nodeport.local:30000"]
            }')" | sudo tee /etc/docker/daemon.json
            sudo service docker restart || true
          fi

          if [ -f "/etc/containers/registries.conf" ]
          then
            echo "INFO:
            Updating registries configuration
            "
            echo "[registries.insecure]
            registries = ['ingress.local','nodeport.local:30000']
            " | sudo tee -a /etc/containers/registries.conf
          fi
        shell: bash
      - name: Start minikube
        run: |
          minikube start --memory=max --cpus=max --vm-driver=docker --extra-config=apiserver.service-node-port-range=80-32000
          minikube addons enable metrics-server
          minikube addons enable ingress
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Setup a minikube docker env
        run: minikube -p minikube docker-env | grep "export" | sed 's/export //' | sed 's/"//g' >> $GITHUB_ENV
      - name: Check code format and generate manifests
        run: |
          make manifests generate fmt vet
        shell: bash
      - name: Prepare Object Storage
        run: |
          if [[ "$COMPONENT_TYPE" == "s3" ]]; then
            echo "CI_TEST_STORAGE=s3" >> $GITHUB_ENV
          fi
          .ci/scripts/prepare-object-storage.sh
        shell: bash
      - name: Deploy pulp-operator to K8s
        run: |
          make local
          kubectl get namespace
          kubectl config set-context --current --namespace=pulp-operator-system
          kubectl apply -f .ci/assets/kubernetes/pulp-admin-password.secret.yaml
          if [[ "$COMPONENT_TYPE" == "ingress" ]]; then
            kubectl apply -f config/samples/simple.ingress.yaml
          elif [[ "$COMPONENT_TYPE" == "telemetry" ]]; then
            kubectl apply -f config/samples/simple.telemetry.yaml
          elif [[ "$COMPONENT_TYPE" == "ldap" ]]; then
            .ci/scripts/ldap_config.sh
            kubectl apply -f config/samples/simple.ldap.yaml
          elif [[ "$COMPONENT_TYPE" == "external-db" ]]; then
            kubectl create ns db
            kubectl apply -f config/samples/external_db.yaml
            kubectl apply -f config/samples/simple-external-db.yaml
          elif [[ "$COMPONENT_TYPE" == "s3" ]]; then
            kubectl config set-context --current --namespace=pulp-operator-system
            kubectl apply -f .ci/assets/kubernetes/pulp-admin-password.secret.yaml
            kubectl apply -f .ci/assets/kubernetes/pulp-object-storage.aws.secret.yaml
            kubectl apply -f config/samples/simple.s3.ci.yaml
          elif [[ "$COMPONENT_TYPE" == "azure" ]]; then
            kubectl config set-context --current --namespace=pulp-operator-system
            kubectl apply -f .ci/assets/kubernetes/pulp-object-storage.azure.secret.yaml
            kubectl apply -f config/samples/simple.azure.ci.yaml
          else
            kubectl apply -f config/samples/simple.yaml
          fi
        shell: bash
      - name: Check and wait pulp-operator deploy
        run: kubectl wait --for condition=Pulp-Operator-Finished-Execution pulp/example-pulp --timeout=900s
        shell: bash
      - name: KubeLinter
        if: github.event_name == 'pull_request'
        run: .ci/scripts/kubelinter.sh
      - name: Test all components
        run: |
          export INGRESS_TYPE=$COMPONENT_TYPE
          .ci/scripts/pulp_tests.sh -m
          if [[ "$COMPONENT_TYPE" == "telemetry" ]]; then
            .ci/scripts/telemetry.sh
          elif [[ "$COMPONENT_TYPE" == "ldap" ]] ; then
            .ci/scripts/ldap_test.sh
          fi
        shell: bash
        env:
          PY_COLORS: '1'
      - name: Backup & Restore
        run: |
          # we do not support backup/restore of external DB
          if [[ "$COMPONENT_TYPE" != "external-db" ]]; then
            .ci/scripts/backup_and_restore.sh -m
          fi
        shell: bash
      - name: Logs
        if: always()
        run: .github/workflows/scripts/show_logs.sh